 export const ErrorCodeEnum ={
   AUTH_EMAIL_ALREADY_EXIST:"AUTH_EMAIL_ALREADY_EXIST",
   AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
   AUTH_USER_NOT_FOUND:"AUTH_USER_NOT_FOUND",

   AUTH_NOT_FOUND:"AUTH_NOT_FOUND",
   AUTH_TOO_MANY_ATTEMPT:"AUTH_TOO_MANY_ATTEMPT",
   AUTH_UNAUTHORISED_ACCESS:"AUTH_NOT_FOUND",
   AUTH_TOKEN_NOT_FOUND: " AUTH_TOKEN_NOT_FOUND",

   ACCESS_UNAUTHORISED_AUTHORISED:"ACCESS_UNAUTHORISED_AUTHORISED",

   VALIDATION_ERROR:"VALIDATION_ERROR",
   RESOURCE_NOT_FOUND:"RESOURCE_NOT_FOUND",

   INTERNAL_SERVER_ERROR:"INTERNAL_SERVER_ERROR"


} as const

export type ErrorCodeTypeEnum = ( keyof typeof ErrorCodeEnum )