const httpConfig =() =>({
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    TOO_MANY_REQUESTS: 429,
    NOT_IMPLEMENTED: 501,
    HTTP_VERSION_NOT_SUPPORTED: 505,
    IM_A_TEAPOT: 418,
    PRECONDITION_FAILED: 412,
    EXPECTATION_FAILED: 417,
    METHOD_NOT_ALLOWED: 405,
    BAD_GATEWAY: 502,
    ACCEPTED: 202,
    RESET_CONTENT: 205,
    PARTIAL_CONTENT: 206,
    MULTI_STATUS: 207,
    ALREADY_REPORTED: 208,
}) as const

export const HTTPSTATUS = httpConfig();
export type HttpCode = (typeof HTTPSTATUS)[ keyof typeof HTTPSTATUS];

